// Generated by purs bundle 0.13.0
var PS = {};
(function(exports) {
  'use strict';

  exports.readAccelerometer = function() {
      return brick.accelerometer().read();
  }
})(PS["Trik"] = PS["Trik"] || {});
(function($PS) {
  // Generated by purs version 0.13.0
  "use strict";
  $PS["Trik"] = $PS["Trik"] || {};
  var exports = $PS["Trik"];
  var $foreign = $PS["Trik"];
  exports["readAccelerometer"] = $foreign.readAccelerometer;
})(PS);
(function($PS) {
  // Generated by purs version 0.13.0
  "use strict";
  $PS["Main"] = $PS["Main"] || {};
  var exports = $PS["Main"];
  var Trik = $PS["Trik"];                
  var solution = function (n) {
      return Trik.readAccelerometer(1);
  };
  var main = solution;
  exports["solution"] = solution;
  exports["main"] = main;
})(PS);
PS["Main"].main();